### ISSUE TITLE
rsyslog 5.8/7.4/8.9 imtcp/TLS hangs on dropped packages

### ISSUE THREAD

**Issue by jeegit** [rsyslog/librelp#12]
We have a central rsyslog server (RHEL6 - 5.8.12) collecting logs from ca. 40 application servers using imtcp over TLS. Under heavy network I/O, rsyslog suddenly stopps logging anything and consumes 100% of one CPU in one thread.

Attaching strace revealed that it runs in a busy loop
```
recvfrom(53, 0x7f527c0d4b70, 5, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
recvfrom(53, 0x7f527c0d4b70, 5, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
recvfrom(53, 0x7f527c0d4b70, 5, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
...
```
in that thread.

I was able to reproduce this with the following test setup: I used two RHEL/CentOS6 machines, one running a rsyslogd instance only listening for TCP/TLS traffic (on port 12514) logging to multiple files, and one running a variable number of rsyslogd instances all listening on distinct sockets, forwarding messages to the first machine without any local logging. I generated load by feeding a text file with long lines (several kBytes) via 'logger' into the sockets in a loop.

The hung state can be provoked in two ways:
1. Stopping one of the clients (`kill -STOP`). It took typically 3-7 attempts until the central server hang in the busy-read loop and nothing from the other clients was logged anymore. Sending CONT to the stopped client resumed normal operation.
2. Dropping network packets via `iptables -A INPUT --protocol tcp -s <client-addr> --sport <client-port> -j DROP`, where the client port identifies just one of the established client connections. Again, it took a few attempts to hang the server.

I reproduced this with the stock CentOS6's rsyslog 5.8.12 version, with the CentOS6's rsyslog7 package (rsyslog 7.4) and rsyslog 8.9 on RHEL6 from the rsyslog.com repository, all using their matching library/module versions.

Attaching a debugger to e.g. 8.9 shows for the busy thread:
```
(gdb) bt
#0  0x00007feb481ccb5c in recv () from /lib64/libpthread.so.0
#1  0x00007feb463494a6 in ?? () from /usr/lib64/libgnutls.so.26
#2  0x00007feb463498a3 in ?? () from /usr/lib64/libgnutls.so.26
#3  0x00007feb463454d1 in _gnutls_recv_int () from /usr/lib64/libgnutls.so.26
#4  0x00007feb465d55dd in gtlsRecordRecv (pThis=0x7feb400027e0) at nsd_gtls.c:509
#5  0x00007feb465d7329 in doRetry (pNsdsel=0x7feb4003b800, pNsd=0x7feb400027e0, waitOp=NSDSEL_RD, 
    pbIsReady=0x7feb45a9e924) at nsdsel_gtls.c:151
#6  IsReady (pNsdsel=0x7feb4003b800, pNsd=0x7feb400027e0, waitOp=NSDSEL_RD, pbIsReady=0x7feb45a9e924)
    at nsdsel_gtls.c:202
#7  0x00007feb467df5f6 in RunSelect (pThis=0x7feb4a444220) at tcpsrv.c:808
#8  Run (pThis=0x7feb4a444220) at tcpsrv.c:885
#9  0x00007feb48857a13 in thrdStarter (arg=0x7feb4a4706e0) at ../threads.c:212
#10 0x00007feb481c59d1 in start_thread () from /lib64/libpthread.so.0
#11 0x00007feb470db8fd in clone () from /lib64/libc.so.6
(gdb) 
```

"Minimal" configuration on the client side
```
$ModLoad imuxsock
$OmitLocalLogging on
$AddUnixListenSocket /somepath/rsyslog/dev/log-LLLL # replaced with client number via script

$MainMsgQueueSize 100000 
$MainMsgQueueType LinkedList
$MainMsgQueueDiscardSeverity 0

$MaxMessageSize 10k

$DefaultNetstreamDriverCAFile /somepath/rsyslog/ca/ca.pem
$DefaultNetstreamDriver gtls         # use gnutls netstream driver
$ActionSendStreamDriverMode 1        # require TLS for the connection
$ActionSendStreamDriverAuthMode anon # server is NOT authenticated

*.* @@(o)test-server:12514
```

On the server side:
```
$DefaultNetstreamDriver gtls
$DefaultNetstreamDriverCAFile /somepath/rsyslog/ca/ca.pem
$DefaultNetstreamDriverCertFile /somepath/rsyslog/ca/dummy-cert.pem
$DefaultNetstreamDriverKeyFile /somepath/rsyslog/ca/dummy-key.pem

$MaxMessageSize 10k

$ModLoad imtcp.so
$InputTCPServerStreamDriverMode 1        # run driver in TLS-only mode
$InputTCPServerStreamDriverAuthMode anon # client is NOT authenticated
$InputTCPServerRun 12514                 # start up listener on port 10514

$template mpLog, "/somepath/var/server.log"
local1.*                                                ?mpLog
local2.*                                                ?mpLog
local3.*                                                ?mpLog
local4.*                                                ?mpLog
local5.*                                                ?mpLog
```

**Comment by jeegit** [comment]
Moving to the right place (rsyslog/rsyslog).
